/**
 * VoyaPulse Mock Data Store
 * Powers destinations, hotels, local experiences, and synergy bundles
 */

const VoyaData = {
  stats: {
    avgOccupancyLift: "+38.4%",
    commissionSaved: "$3.8M+",
    localBusinessesSupported: "2,840+",
    co2DispersalScore: "94/100",
    activeHotels: "1,420+",
    verifiedGuides: "3,650+"
  },

  destinations: [
    {
      id: "cilento",
      name: "Cilento Biosphere Coast",
      country: "Italy",
      region: "Campania",
      alternativeTo: "Amalfi Coast (98% crowded)",
      badge: "Smart Dispersal Highlight",
      tagline: "Unspoiled Mediterranean coves, ancient olive groves & zero crowds",
      description: "Just south of the saturated Amalfi coast lies Cilento: a UNESCO biosphere reserve where ancient Greek temples meet secluded sapphire bays and farm-to-table culinary heritage.",
      image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
      ecoScore: 96,
      localEconRetention: "92%",
      vibe: ["Nature", "Culinary", "Workation", "Heritage"],
      avgOffPeakDiscount: "35%",
      bestFor: "Remote workers & slow travelers seeking authentic Italian coastal life."
    },
    {
      id: "takayama",
      name: "Takayama & Hida Highlands",
      country: "Japan",
      region: "Gifu Prefecture",
      alternativeTo: "Kyoto (Severe overtourism)",
      badge: "Cultural Preservation",
      tagline: "Edo-period wooden merchant houses, alpine hot springs & artisan sake",
      description: "Nestled in the Japanese Alps, Takayama offers intact Edo-period streets, centuries-old sake breweries, and morning artisan markets without the shoulder-to-shoulder Kyoto crowds.",
      image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
      ecoScore: 98,
      localEconRetention: "95%",
      vibe: ["Heritage", "Artisan", "Culinary", "Wellness"],
      avgOffPeakDiscount: "40%",
      bestFor: "Travelers yearning for authentic Japanese craft, ryokans, and tranquil hot springs."
    },
    {
      id: "umbria",
      name: "Valnerina & Umbrian Valleys",
      country: "Italy",
      region: "Umbria",
      alternativeTo: "Florence / Siena Axis",
      badge: "Slow Travel & Agro-Tourism",
      tagline: "Medieval hill towns, wild black truffles & monastery sanctuaries",
      description: "Known as the 'Green Heart of Italy', Umbria provides lush rolling hills, wild truffle foraging with local truffle hunters, and monastic sanctuaries at half the tourist density of Tuscany.",
      image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80",
      ecoScore: 94,
      localEconRetention: "89%",
      vibe: ["Culinary", "Nature", "Heritage", "Workation"],
      avgOffPeakDiscount: "32%",
      bestFor: "Foodies, writers, and couples desiring quiet vineyards and rustic luxury."
    },
    {
      id: "lombok",
      name: "South Lombok Eco-Peninsula",
      country: "Indonesia",
      region: "West Nusa Tenggara",
      alternativeTo: "Canggu / Seminyak Bali",
      badge: "Regenerative Eco-Hub",
      tagline: "Pristine surf breaks, bamboo architecture & Sasak community immersion",
      description: "An eco-conscious paradise of white sand beaches and solar-powered bamboo lodges, Lombok keeps tourism benefits directly in village cooperatives while avoiding Bali's traffic gridlock.",
      image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
      ecoScore: 97,
      localEconRetention: "94%",
      vibe: ["Adventure", "Wellness", "Workation", "Nature"],
      avgOffPeakDiscount: "42%",
      bestFor: "Digital nomads, surfers, and wellness enthusiasts wanting pure island tranquility."
    },
    {
      id: "taos",
      name: "Taos High Desert Mesa",
      country: "USA",
      region: "New Mexico",
      alternativeTo: "Sedona / Scottsdale",
      badge: "Indigenous & Art Heritage",
      tagline: "Historic adobe pueblos, sacred mountain light & thriving artist colonies",
      description: "A thousand-year-old living community and epicenter of Southwestern creative arts, Taos provides high-altitude serenity, geothermal mineral springs, and rich indigenous cultural history.",
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      ecoScore: 91,
      localEconRetention: "88%",
      vibe: ["Artisan", "Heritage", "Adventure", "Wellness"],
      avgOffPeakDiscount: "30%",
      bestFor: "Creatives, spiritual seekers, and hikers seeking expansive starry desert nights."
    }
  ],

  hotels: [
    {
      id: "hotel-palazzo-cilento",
      name: "Palazzo San Nicola Eco-Resort",
      destinationId: "cilento",
      location: "San Mauro Cilento, Italy",
      type: "Boutique Heritage Stay",
      rating: 4.9,
      reviewsCount: 142,
      pricePerNight: 145,
      standardOtaPrice: 195,
      image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
      amenities: ["Fiber Wi-Fi (300Mbps)", "Ergonomic Desk", "Organic Olive Orchard", "Solar Heated Pool", "EV Charging"],
      offPeakPerk: "Complimentary weekday co-working lounge pass + organic olive oil tasting",
      sustainableFeature: "100% solar powered, zero single-use plastics, hyper-local hiring",
      hostName: "Marco & Giulia",
      hostBio: "Third-generation olive millers committed to revitalizing our ancient village."
    },
    {
      id: "hotel-yamano-takayama",
      name: "Yamano Mori Ryokan & Spa",
      destinationId: "takayama",
      location: "Takayama Old Quarter, Japan",
      type: "Traditional Onsen Ryokan",
      rating: 4.95,
      reviewsCount: 208,
      pricePerNight: 180,
      standardOtaPrice: 260,
      image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
      amenities: ["Natural Geothermal Onsen", "Tatami Work Nook", "Kaiseki Breakfast", "Cedar Bath", "Bicycle Fleet"],
      offPeakPerk: "Private onsen evening reservation + guided morning artisan market tour",
      sustainableFeature: "Geothermal district heating, heirloom seasonal agriculture sourcing",
      hostName: "Master Kenji Sato",
      hostBio: "Preserving authentic Hida woodworking and traditional hospitality for 40 years."
    },
    {
      id: "hotel-borgo-umbria",
      name: "Borgo delle Rose Agro-Villa",
      destinationId: "umbria",
      location: "Spello, Umbria, Italy",
      type: "Vineyard Estate Stay",
      rating: 4.88,
      reviewsCount: 119,
      pricePerNight: 130,
      standardOtaPrice: 185,
      image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
      amenities: ["High-speed Starlink Wi-Fi", "Private Kitchenette", "Wine Cellar", "Terrace with Valley Views"],
      offPeakPerk: "Free truffle hunting dog excursion with master forager Matteo",
      sustainableFeature: "Biodynamic organic vineyard, rain harvesting system",
      hostName: "Chiara & Matteo",
      hostBio: "Passionate about preserving biodiversity and Umbrian slow-food culinary traditions."
    },
    {
      id: "hotel-taman-lombok",
      name: "Taman Laut Bamboo Sanctuary",
      destinationId: "lombok",
      location: "Kuta Coastal Hills, Lombok",
      type: "Eco-Nomad Villa",
      rating: 4.92,
      reviewsCount: 187,
      pricePerNight: 95,
      standardOtaPrice: 150,
      image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80",
      amenities: ["Dedicated Nomads Co-Working Hub", "Ocean-View Yoga Shala", "Surfing Locker", "Electric Scooters"],
      offPeakPerk: "Daily breakfast included + 2 free surf coaching sessions with local champion",
      sustainableFeature: "100% sustainable engineered bamboo construction, permaculture farm",
      hostName: "Wayan & Aisyah",
      hostBio: "Creating high-wage green jobs for local youth through sustainable hospitality."
    },
    {
      id: "hotel-mesa-taos",
      name: "El Monte Adobe Sanctuary",
      destinationId: "taos",
      location: "Taos Foothills, New Mexico",
      type: "Artisan Adobe Retreat",
      rating: 4.85,
      reviewsCount: 96,
      pricePerNight: 160,
      standardOtaPrice: 220,
      image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
      amenities: ["Kiva Fireplace", "Artist Studio Space", "Saltwater Hot Tub", "Dark Sky Stargazing Deck"],
      offPeakPerk: "Pueblo pottery workshop access + private stargazing binoculars set",
      sustainableFeature: "Thermal adobe mass heating, native xeriscaping water conservation",
      hostName: "Elena & David",
      hostBio: "Local sculptors dedicated to sharing Native Southwestern cultural roots."
    }
  ],

  experiences: [
    {
      id: "exp-cilento-truffle",
      destinationId: "cilento",
      title: "Ancient Olive Pressing & Mediterranean Longevity Feast",
      guide: "Nonna Rosa & Vincenzo",
      type: "Culinary & Cultural",
      duration: "3.5 Hours",
      price: 48,
      otaPrice: 75,
      badge: "100% Direct to Host",
      description: "Walk through 300-year-old olive groves, see traditional stone pressing, and dine on wood-fired sourdough and sheep milk cheeses.",
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "exp-takayama-sake",
      destinationId: "takayama",
      title: "Centuries-Old Sake Cellar Tasting & Cedar Craft Workshop",
      guide: "Shinjiro Funasaka",
      type: "Artisan & Heritage",
      duration: "3 Hours",
      price: 52,
      otaPrice: 85,
      badge: "Living Heritage",
      description: "Go behind the velvet ropes of a 200-year-old brewery, sample 6 unpasteurized sakes, and carve your own cypress sake cup.",
      image: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "exp-umbria-truffle",
      destinationId: "umbria",
      title: "Secret Woods Wild Truffle Hunt with Trained Lagotto Dogs",
      guide: "Matteo & his dog Pippo",
      type: "Nature & Foraging",
      duration: "4 Hours",
      price: 55,
      otaPrice: 90,
      badge: "Zero-Carbon Adventure",
      description: "Follow scent hounds through ancient oak forests to unearth black summer truffles, followed by fresh handmade tagliolini in a rustic cabin.",
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "exp-lombok-weaving",
      destinationId: "lombok",
      title: "Sukarara Village Hand-Weaving & Coral Restoration Snorkel",
      guide: "Nurul & Ocean Guardians",
      type: "Community & Ocean Eco",
      duration: "4.5 Hours",
      price: 38,
      otaPrice: 65,
      badge: "Reef Restoration",
      description: "Learn indigenous songket weaving directly from women village elders and participate in transplanting baby corals onto a protected reef nursery.",
      image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "exp-taos-pueblo",
      destinationId: "taos",
      title: "Sacred Adobe Architecture & Micaceous Clay Pottery Workshop",
      guide: "Kateri (Taos Pueblo Artisan)",
      type: "Indigenous Culture",
      duration: "3 Hours",
      price: 60,
      otaPrice: 95,
      badge: "Native Owned",
      description: "Learn the spiritual art of harvesting local mica-infused clay, shaping vessels by hand without a wheel, and baking bread in an outdoor horno.",
      image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80"
    }
  ],

  synergyBundles: [
    {
      id: "bundle-cilento-revive",
      title: "The Mediterranean Revival Workation & Feast",
      destinationId: "cilento",
      destinationName: "Cilento Coast, Italy",
      nights: 4,
      hotelName: "Palazzo San Nicola Eco-Resort",
      hotelPricePerNight: 145,
      includedExperience: "Ancient Olive Pressing & Mediterranean Longevity Feast",
      experiencePrice: 48,
      includedTransport: "Regional Hybrid Train Pass & Coastal E-Bike Rental",
      transportPrice: 40,
      totalUnbundledPrice: 668,
      synergyBundlePrice: 495,
      totalSavings: 173,
      hotelNetProfitBoost: "+28% vs OTA sale",
      co2Score: "42 kg CO2 saved via regional transit",
      badge: "Best Seller: Workation & Slow Food",
      tags: ["4 Nights Midweek", "Boutique Hotel", "Culinary Experience", "E-Bike Included"]
    },
    {
      id: "bundle-takayama-heritage",
      title: "The Alpine Artisan & Onsen Immersion",
      destinationId: "takayama",
      destinationName: "Takayama & Hida, Japan",
      nights: 3,
      hotelName: "Yamano Mori Ryokan & Spa",
      hotelPricePerNight: 180,
      includedExperience: "Centuries-Old Sake Cellar Tasting & Cedar Craft Workshop",
      experiencePrice: 52,
      includedTransport: "Scenic Alpine Rail Pass & City Heritage Cruiser",
      transportPrice: 55,
      totalUnbundledPrice: 647,
      synergyBundlePrice: 480,
      totalSavings: 167,
      hotelNetProfitBoost: "+34% vs OTA sale",
      co2Score: "58 kg CO2 saved via electric rail",
      badge: "Cultural Preservation Hero",
      tags: ["3 Nights", "Private Onsen", "Sake Tasting", "Alpine Rail"]
    },
    {
      id: "bundle-lombok-regen",
      title: "The Regenerative Nomad & Surf Retreat",
      destinationId: "lombok",
      destinationName: "South Lombok, Indonesia",
      nights: 5,
      hotelName: "Taman Laut Bamboo Sanctuary",
      hotelPricePerNight: 95,
      includedExperience: "Village Hand-Weaving & Coral Restoration Snorkel",
      experiencePrice: 38,
      includedTransport: "Solar E-Scooter Rental for 5 Days",
      transportPrice: 45,
      totalUnbundledPrice: 558,
      synergyBundlePrice: 399,
      totalSavings: 159,
      hotelNetProfitBoost: "+38% vs OTA sale",
      co2Score: "76 kg CO2 offset with reef restoration",
      badge: "Eco-Nomad Favorite",
      tags: ["5 Nights Midweek", "Bamboo Villa", "Coral Snorkel", "Solar Scooter"]
    },
    {
      id: "bundle-umbria-truffle",
      title: "The Secret Truffle Valley & Hilltowns Pass",
      destinationId: "umbria",
      destinationName: "Umbrian Valleys, Italy",
      nights: 3,
      hotelName: "Borgo delle Rose Agro-Villa",
      hotelPricePerNight: 130,
      includedExperience: "Secret Woods Wild Truffle Hunt with Lagotto Dogs",
      experiencePrice: 55,
      includedTransport: "Electric Fiat 500 Country Rental (3 Days)",
      transportPrice: 75,
      totalUnbundledPrice: 520,
      synergyBundlePrice: 385,
      totalSavings: 135,
      hotelNetProfitBoost: "+26% vs OTA sale",
      co2Score: "100% electric local mobility",
      badge: "Gastronomic Escape",
      tags: ["3 Nights", "Agro-Villa", "Truffle Hunt", "EV Included"]
    }
  ]
};

if (typeof window !== 'undefined') {
  window.VoyaData = VoyaData;
}
